openapi: 3.0.3
info:
  title: Swagger Attendance
  version: 1.0.0
  description: "考勤数据处理接口"
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://student.swagger.io/v2
  - url: http://student.swagger.io/v2
tags:
  - name: AttendanceServer
    description: "考勤"
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /v1/attendance/statistics:
    post:
      tags:
        - AttendanceServer
      summary: "统计原始考勤数据"
      operationId: processOriginData
      requestBody:
        description: "需要转换的原始信息"
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                originFile:
                  type: string
                  format: binary
                needYear:
                  type: integer
                  format: int32
                  minimum: 2000
                  maximum: 2030
                  example: 2024
                needMonth:
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 12
                  example: 5
      responses:
        200:
          description: OK
          content:
            multipart/form-data:
              schema:
                type: object
        201:
          description: Created
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden